font:
    normal:
      # family: FuraCode Nerd Font Mono
      family: RobotoMono Nerd Font
      # family: Monoid Nerd Font Mono
    size: 10
# colors:
#     primary:
#         # foreground: '#ffffff'
#         foreground: '#B3B1AD'
#           # background: '#121212'
#           # background: '#0A0E14'
#         background: '#1d2021'
#     # vi_mode_cursor:
#     #     text: '#FFFFFF'
#     #     cursor: '#000000'
#     cursor:
#         text: CellBackground
#         cursor: CellForeground
#     vi_mode_cursor:
#         text: CellBackground
#         cursor: CellForeground
#     normal:
#         black: '#0d1016'
#         red: '#FF3333'
#         green: '#C2D94c'
#         yellow: '#E6B450'
#         blue: '#39bae6'
#         magenta: '#F07178'
#         cyan: '#6994bf'
#         white: '#B3b1ad'
#     bright:
#         black: '#333f56'
#         red: '#ff9999'
#         green: '#dfeba0'
#         yellow: '#f3daa9'
#         blue: '#94daf1'
#         magenta: '#facdd0'
#         cyan: '#b0c7de'
#         white: '#e4e3e2'
colors:
  # Default colors
  primary:
    # hard contrast: background = '0x1d2021'
    background: '0x282828'
    # soft contrast: background = '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xCC241D'
    green:   '0x98971A'
    yellow:  '0xD79921'
    blue:    '0x458588'
    magenta: '0xB16286'
    cyan:    '0x689D6A'
    white:   '0xA89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
cursor:
    style: Block
    text: CellBackground
    cursor: CellForeground
vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
mouse:
    hide_when_typing: true
key_bindings:
    - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
    - { key: Left,     mods: Shift,   chars: "\x1b[1;2D" }
