font:
    normal:
        family: FiraCode Nerd Font
    size: 12
colors:
    primary:
        # foreground: '#ffffff'
        foreground: '#B3B1AD'
          # background: '#121212'
        background: '#0A0E14'
    # vi_mode_cursor:
    #     text: '#FFFFFF'
    #     cursor: '#000000'
    cursor:
        text: CellBackground
        cursor: CellForeground
    vi_mode_cursor:
        text: CellBackground
        cursor: CellForeground
    normal:
        black: '#0d1016'
        red: '#FF3333'
        green: '#C2D94c'
        yellow: '#E6B450'
        blue: '#39bae6'
        magenta: '#F07178'
        cyan: '#6994bf'
        white: '#B3b1ad'
    bright:
        black: '#333f56'
        red: '#ff9999'
        green: '#dfeba0'
        yellow: '#f3daa9'
        blue: '#94daf1'
        magenta: '#facdd0'
        cyan: '#b0c7de'
        white: '#e4e3e2'
cursor:
    style: Block
mouse:
    hide_when_typing: true
key_bindings:
    - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }
    - { key: Left,     mods: Shift,   chars: "\x1b[1;2D" }
