theme = "modern"

[icons]
name = "awesome"

[icons.overrides]
memory_mem = " "
cpu = " "

[[block]]
block = "net"
device = "enp2s0"
ip = true
speed_up = true
speed_down = true
interval = 2

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MUg} GB / {MTg} GB"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "music"
buttons = ["play", "next"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
